/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWatchesRouteImport } from './routes/_auth/watches'
import { Route as AuthWatchesNewRouteImport } from './routes/_auth/watches_.new'
import { Route as AuthWatchesIdRouteImport } from './routes/_auth/watches_.$id'
import { Route as AuthWatchesIdEditRouteImport } from './routes/_auth/watches_.$id_.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWatchesRoute = AuthWatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWatchesNewRoute = AuthWatchesNewRouteImport.update({
  id: '/watches_/new',
  path: '/watches/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWatchesIdRoute = AuthWatchesIdRouteImport.update({
  id: '/watches_/$id',
  path: '/watches/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWatchesIdEditRoute = AuthWatchesIdEditRouteImport.update({
  id: '/watches_/$id_/edit',
  path: '/watches/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/watches': typeof AuthWatchesRoute
  '/watches/$id': typeof AuthWatchesIdRoute
  '/watches/new': typeof AuthWatchesNewRoute
  '/watches/$id/edit': typeof AuthWatchesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/watches': typeof AuthWatchesRoute
  '/watches/$id': typeof AuthWatchesIdRoute
  '/watches/new': typeof AuthWatchesNewRoute
  '/watches/$id/edit': typeof AuthWatchesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/_auth/watches': typeof AuthWatchesRoute
  '/_auth/watches_/$id': typeof AuthWatchesIdRoute
  '/_auth/watches_/new': typeof AuthWatchesNewRoute
  '/_auth/watches_/$id_/edit': typeof AuthWatchesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/watches'
    | '/watches/$id'
    | '/watches/new'
    | '/watches/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/watches'
    | '/watches/$id'
    | '/watches/new'
    | '/watches/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/sign-in'
    | '/_auth/watches'
    | '/_auth/watches_/$id'
    | '/_auth/watches_/new'
    | '/_auth/watches_/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/watches': {
      id: '/_auth/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof AuthWatchesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/watches_/new': {
      id: '/_auth/watches_/new'
      path: '/watches/new'
      fullPath: '/watches/new'
      preLoaderRoute: typeof AuthWatchesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/watches_/$id': {
      id: '/_auth/watches_/$id'
      path: '/watches/$id'
      fullPath: '/watches/$id'
      preLoaderRoute: typeof AuthWatchesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/watches_/$id_/edit': {
      id: '/_auth/watches_/$id_/edit'
      path: '/watches/$id/edit'
      fullPath: '/watches/$id/edit'
      preLoaderRoute: typeof AuthWatchesIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthWatchesRoute: typeof AuthWatchesRoute
  AuthWatchesIdRoute: typeof AuthWatchesIdRoute
  AuthWatchesNewRoute: typeof AuthWatchesNewRoute
  AuthWatchesIdEditRoute: typeof AuthWatchesIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWatchesRoute: AuthWatchesRoute,
  AuthWatchesIdRoute: AuthWatchesIdRoute,
  AuthWatchesNewRoute: AuthWatchesNewRoute,
  AuthWatchesIdEditRoute: AuthWatchesIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
